sudo: false
language: go
go:
  - 1.9
script:
  - make test vet
before_deploy:
  - ./scripts/build.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DJXTbl431ICKbT57hhPr5l+XSbNesPle8sUib3Bu4vI6JJ7yJcMnyDLzogmdAyE9c+V47G+aBneUxXw8rcODK6HO66CmP1ci3ZM4gZOBPNGIj18fYMWbKuLnL0VzTBWhJnRMSqfpvSqWuZxQwR257wwWc9+mqh+miuqaN9DJgIYYNwf88UOEMkLzAHAhu1qklBl2hHvzyBZtK5aOvlMYQFhbM1C7f0uODZBgl1hQ0qjVKGzO//698BN00HHW0XIDqlZQGThTZRGliE9H6jKFX8b9Z7fabViWgGzeYozeyhTJq/m0tkoZ0fKJDQQTRqUW1hq/kzpF9KdUVwdY6hnBlfiV/d+XaD8t6sv1qYMYeIeAzsY75Z84ThcZab8mEv4AHI1THuFLGRRJ6XE7ktaMBp84vmfkhM4nflZfaSgJVydr2fLnMqnLUXVrQdZXiru0WCb+nXU0rfi+/8W+wOn0+W8EGYHxzNJtQmgTCoqx4u0tn500ewPmpkwtXlHcBxyqjA3NiVa6qZCKrYXe/i3PYE9jDBP9u0JH4hK+cNFYA6l/U/4bmuRKaYH+W/mQdtmptDfcDJnJwoGmNtlYgl+xqdkY1tW2zrBoSu+ojVA2tayOtpBQgroN+mj+ZTMwgCPUSVgp9vN/8I5JjSRYWRSF8c3iDomnUmStAabRp2Dfsng=
  file_glob: true
  file: 'pkg/*.zip'
  on:
    all_branches: true
    tags: true
