sudo: false
language: go
go:
  - 1.7
script:
  - make test vet
before_deploy:
  - ./scripts/build.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: O3AidKU+qH7OL3MAZTAXXuDEQENjxGUWYYbShzZlw9YykJXr9z5D2rLmVlfi6mf/pTnbZ1k7qLK9MNWJDnBXfvbLXef4z0gJZP6ZSCnPfw0qguRfFZTGl2qm/xm8H/pKGMmlFJ1fe1VXpVYFpXcIoqIZHkxvxLFlffE2fWH84vVM3M/4vS8tKlamu0rhFf2D2tv2EmKGRAhBGHMgsjtqwx5rGERrYp7wZSDUuNfU6aNF7YgJlu+WAKzE3Q7KCPZrzddxs+RMjYD909VDrGO6sEhrS33FU+M10wsFC7eGL7HdjY3DubnRuxciJRgOHom1ieT1DX3EMyMKxsgWy0S4J8tzlANnycSdY1YyV/tkqLcFMDVF11lPI2Yt0xmXLAztvgobG03Y8qoTZxg3LFrh3Siytgl50466kPfQFZErlyjFCDox38+/BRLI7vQCDCDRWZZdK5ae+v4HiUPHou9/YWQAf+bbsqphlp3Jrp4znR0htKZEGEj6jMbz8rPGpcCpT4xByBLW1MequpivkHTAMazHFYeO/2X7fyZwjcpZj7qW4mEuelh5j6SfwXzTdHCDPk6R74Lnt/IR5ZH5j1szZKP3Si+v0BaSRDAGGtVYJUMnsqHVzP/chPzN5qtjhYsfa8olcbda/2igvtIFPmJ43UHczYvPekH4WC7EBeTxtbU=
  file_glob: true
  file: 'pkg/*.zip'
  on:
    all_branches: true
    tags: true
